//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.testProcject
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Man.
    /// </summary>
    //  *** Start programmer edit section *** (Man CustomAttributes)

    //  *** End programmer edit section *** (Man CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Man : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (Man CustomMembers)

        //  *** End programmer edit section *** (Man CustomMembers)

    }
}
